replicaCount: 1

image:
  repository: postgres
  tag: "13"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 5432

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

postgres:
  database: "app"
  user: "appuser"
  password: "apppassword"

persistence:
  enabled: false
  storageClass: ""
  size: 8Gi

nodeSelector: {}
tolerations: []
affinity: {}

